const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    SET_LANGUAGES: 'SET_LANGUAGES',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS :'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    //admin
    GENDER_OK : 'GENDER_OK',
    SUCCESS_GENDER : 'SUCCESS_GENDER',
    FAIL_GENDER : 'FAIL_GENDER',
    //position 
    POSITION_OK : 'POSITION_OK',
    SUCCESS_POSITION : 'SUCCESS_POSITION',
    FAIL_POSITION : 'FAIL_POSITION',
    //role
    ROLE_OK : 'ROLE_OK',
    SUCCESS_ROLE : 'SUCCESS_ROLE',
    FAIL_ROLE : 'FAIL_ROLE',
    // CRUDuser
    USER_SAVE:'USER_SAVE',
    USER_FAILED:'USER_FAILED',
    SHOW_SAVE:'SHOW_SAVE',
    SHOW_FAILED:'SHOW_FAILED',
    UPDATE_SAVE:'UPDATE_SAVE',
    UPDATE_FAILED:'UPDATE_FAILED',
    DELETE_SAVE:'DELETE_SAVE',
    DELETE_FAILED:'DELETE_FAILED',
    GET_TIME_SUCCESS:'GET_TIME_SUCCESS',
    GET_TIME_ERROR:'GET_TIME_ERROR',
    // homepage
    DOCTOR_SUCCESS : 'DOCTOR_SUCCESS',
    DOCTOR_FAIL : 'DOCTOR_FAIL',
    DOCTOR_SELECT_SUCCESS: 'DOCTOR_SELECT_SUCCESS',
    DOCTOR_SELECT_FAIL: 'DOCTOR_SELECT_FAIL',
    SUBMIT_DOCTOR_SUCCESS:'SUBMIT_DOCTOR_SUCCESS',
    SUBMIT_DOCTOR_ERROR: 'SUBMIT_DOCTOR_ERROR',
    DOCTOR_DETAIL_SUCCESS:'DOCTOR_DETAIL_SUCCESS',
    DOCTOR_DETAIL_FAIL: 'DOCTOR_DETAIL_FAIL',
    CALL_AP_TIME_SUCCESS: 'CALL_AP_TIME_SUCCESS',
    CALL_AP_TIME_FAIL: 'CALL_AP_TIME_FAIL',


})

export default actionTypes;